--- 
- name: Install MySQL server
  yum:
    name: mariadb-server
    state: present

- name: Start and enable MySQL
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Secure MySQL installation
  mysql_secure_installation:
    login_user: root
    login_password: ''
    root_password: 'secure_root_password'
    state: present
    change_root_password: yes
    remove_anonymous_users: yes
    disallow_root_login_remotely: yes
    remove_test_db: yes

